default_root_dir: ${paths.output_dir}

logger: true
enable_checkpointing: true
callbacks: null

min_epochs: 1 # prevents early stopping
max_epochs: 100

# run validation steps immediately to avoid having to wait for the end of the epoch to find out you have bugs / exceptions
num_sanity_val_steps: 2

# acceleration
accelerator: auto
devices: 1
gpus: null
auto_select_gpus: false
tpu_cores: null
ipus: null

# mixed precision for extra speed-up
precision: 32

# set True to ensure deterministic results: makes training slower but gives more reproducibility than just setting seeds
deterministic: True

gradient_clip_val: null
gradient_clip_algorithm: null
num_nodes: 1
num_processes: null
enable_progress_bar: true
overfit_batches: 0.0
track_grad_norm: -1
check_val_every_n_epoch: 1
fast_dev_run: false
accumulate_grad_batches: null
max_steps: -1
min_steps: null
max_time: null
limit_train_batches: null
limit_val_batches: null
limit_test_batches: null
limit_predict_batches: null
val_check_interval: null
log_every_n_steps: 100
strategy: null
sync_batchnorm: false
enable_model_summary: true
weights_save_path: null
resume_from_checkpoint: null
profiler: null
benchmark: null
reload_dataloaders_every_n_epochs: 0
auto_lr_find: false
replace_sampler_ddp: true
detect_anomaly: false
auto_scale_batch_size: false
plugins: null
amp_backend: native
amp_level: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
