# @package _global_

defaults:
  - paths: default.yaml
  - hydra: default.yaml
  - extras: default.yaml
  - callbacks: default.yaml
  - logger: tensorboard.yaml
  - model: wgangp.yaml
  - datamodule: cifar-10.yaml
  - privacy: default.yaml
  - _self_

stage: fit # fit, validate, test, assess, attack
tag: wgangp-cifar-10-${stage}

seed_everything: true
trainer:
  enable_checkpointing: true
  accelerator: auto
  num_sanity_val_steps: 2
  log_every_n_steps: 50
  min_epochs: 10
  max_epochs: 1000
  callbacks:
    - _target_: brainiac_2.callbacks.mace.MaceCallback
      run_every_n_epochs: 1
      run_immediately: False
      local: True
      query:
        _target_: brainiac_2.query.Flatten
        model_at: "discriminator"
ckpt_path: null
