_target_: brainiac_2.datasets.CIFARDataModule
data_dir: ${paths.data_dir}
batch_size: 32
num_workers: 1
cifar_n: 10
split:
- 45000
- 5000
transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: 64
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]